name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

env:
  SCRIPTS_PATH : ../../scripts/

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Donner les droits d'exécution
        run: chmod +x ${SCRIPTS_PATH}/buildsite.sh ${SCRIPTS_PATH}/buildpage.sh

      - name: Construire le site
        run: ${SCRIPTS_PATH}/buildsite.sh

      - name: Publier les fichiers
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
